### ISSUE TITLE
Forestry wood can be split into 4 planks.

### ISSUE THREAD

**Issue by Nexses** [LordMonoxide/gradient#101]
The logs in the forestry mod can be split into 4 planks without a tool.

**Comment by LordMonoxide** [comment]
This applies to all wood except for vanilla

**Comment by LordMonoxide** [comment]
I've been able to genericise the algorithm to remove any wood that's been registered properly.  Biomes o' Plenty wood is.  Forestry and Natura wood, unfortunately, are not.  I'll commit the changes that support BoP wood for now, and try to add special case handling for the other mods later.
