### ISSUE TITLE
Vanilla/BoP fences, etc. require mattock, Natura fences, etc. require fisting

### ISSUE THREAD

**Issue by CaitlinTheAwesome** [LordMonoxide/gradient#107]
Can't break wooden objects made with Natura objects. Tested door, steps, fence using stone mattock.

**Comment by LordMonoxide** [comment]
@CaitlinTheAwesome @Nexses 
If you ever run into stuff like this, can you spawn in the debug item (looks like a nether star) and right-click on the object with it?  It'll dump a bunch of info about the blocks (you may need to scroll up in the chat logs).  I need info on the harvest levels.

**Comment by LordMonoxide** [comment]
Update: my code is NOT blocking breaking Natura stuff... gonna have to dig deeper

**Comment by CaitlinTheAwesome** [comment]
nice title. lol

**Comment by LordMonoxide** [comment]
Closed by #447
