### ISSUE TITLE
Enhancement - A Trivial Use for Pebbles

### ISSUE THREAD

**Issue by CaitlinTheAwesome** [LordMonoxide/gradient#115]
I notice you have a giant chest of pebbles. After you're done with stone tools, there should still be some use for pebbles, even if it's just decorative, so it doesn't become a 100% junk resource.

Ideas/examples:
- craft 9 pebbles together to make either one cobblestone or one gravel
- right click on a block to place pebbles as stone paths (saw one in another mod before but forget where)
- interchangeable with flint for making arrows
- some sort of stupid craftable decorative statuette or paperweight or pet rock or something?

Yeah I'm out of ideas. Anyone got anything else?

**Comment by LordMonoxide** [comment]
I like the idea of paths

**Comment by CaitlinTheAwesome** [comment]
figured out where I saw it before. Something similar to that perhaps
http://mrcrayfishs-furniture-mod.wikia.com/wiki/Stone_Path

**Comment by Nexses** [comment]
Turn 1 into a button, turn a cobble stone into 9 pebbles,
