### ISSUE TITLE
Enhancement: Bellows

### ISSUE THREAD

**Issue by CaitlinTheAwesome** [LordMonoxide/gradient#117]
So we were chatting last night about potentially making heat transfer elastic between adjacent furnaces, so that if one furnace were beside a hotter furnace, the hotter one's presence would cause the cooler one to heat up faster, and that got me thinking about the whole situation...

It took me several Minecraft days to reach 1200 degrees, and the whole passing of time aspect made things feel a little exaggerated. I was thinking, "there's no way blacksmiths just sat around waiting for things to heat up for half a day... OH WAIT, BELLOWS ARE A THING."

**Proposed crafting recipe:**
(ignore failed table formatting lol I tried)

| stick  | planks | (blank)
| ------------- | ------------- | -------------
| (blank)  | **leather** | **nozzle**
| **stick**  | **planks**  | (blank)

Where nozzle could be its own recipe (maybe use the hopper recipe as a starting point and adjust as needed), or an ingot or nugget...

**Function:** 
I figure you can maybe right click on a burning furnace with it in hand to give that furnace a boost in temperature (similar to the effect a fire starter has on an unlit furnace or fire). The boost couldn't go above peak temperature for the burning medium, but it would help it to get there faster so that you don't have to waste so much material getting things hot enough to work.

**Comment by Mavkain** [comment]
This would be awesome as I'm struggling to even hit 700deg. So I can use the coal nuggets. Then I'm still going to have to sit here and feed it that.

**Comment by LordMonoxide** [comment]
I'll finally get around to tackling this once I finish the 1.13 update
