### ISSUE TITLE
If your hammer breaks when breaking a block, you get the block itself instead of pebbles/nuggets

### ISSUE THREAD

**Issue by LordMonoxide** [LordMonoxide/gradient#35]
1. Have a hammer with 1 durability left
2. Use it to mine iron ore

Expected: you get pebbles and iron nuggets
Actual: you get the iron ore block as if you mined it with a regular pickaxe

**Comment by LordMonoxide** [comment]
This is currently blocked by MinecraftForge/MinecraftForge#4384

**Comment by alcatrazEscapee** [comment]
Hi. I am the author of No Tree Punching. I have found a potential workaround for this problem, if you want to implement something similar. Basically it involves using a capability to store a copy of the tool broken on breaking the block (before the tool takes damage) and then retrieves it later to check for harvest drops.

Capability implementation [here](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.12-2.0.0/src/main/java/com/alcatrazescapee/notreepunching/common/capability/CapabilityPlayerItem.java), saving the tool [here](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.12-2.0.0/src/main/java/com/alcatrazescapee/notreepunching/ModEventHandler.java#L51), and using it [here](https://github.com/alcatrazEscapee/no-tree-punching/blob/1.12-2.0.0/src/main/java/com/alcatrazescapee/notreepunching/ModEventHandler.java#L92).

**Comment by LordMonoxide** [comment]
I **finally** got around to implementing your suggestion.  Thanks!  Worked like a charm.
