### ISSUE TITLE
Crafting reagents in player slots 

### ISSUE THREAD

**Issue by Mavkain** [LordMonoxide/gradient#595]
Opening the crafting window and clicking on the stone pickaxe recipe it does not put all reagents in the crafting grid. The 3 pebbles go into the grid but the hardened stick is in the player head slot. The leather cord is in the player foot slot.

**Comment by LordMonoxide** [comment]
Interesting... the 3x3 crafting grid code is pretty hacky.  I've never actually used the crafting book.  I'll have to take a look at how it works and see what I can do.

**Comment by Mavkain** [comment]
Actually I found that this only happens when using the crafting area in the inventory and not the crafting table.

**Comment by LordMonoxide** [comment]
Closing this in favour of #616.  JEI has recipes for everything (including things like fuel, mixing basin, etc.) and the recipe book code isn't flexible enough for me to fix this.
