### ISSUE TITLE
Armour duplicating

### ISSUE THREAD

**Issue by Mavkain** [LordMonoxide/gradient#608]
When you open the inventory and click a recipe that would have required the full 3x3
It will duplicate what's in the armour slots.

**Comment by LordMonoxide** [comment]
Is this when using the recipe book?

**Comment by Mavkain** [comment]
Yes it is. I can't remember recipes so I use the book.

**Comment by LordMonoxide** [comment]
Closing this in favour of #616.  JEI has recipes for everything (including things like fuel, mixing basin, etc.) and the recipe book code isn't flexible enough for me to fix this.
