### ISSUE TITLE
Can't remove items from left side of mixing basin

### ISSUE THREAD

**Issue by CaitlinTheAwesome** [LordMonoxide/gradient#784]
Steps to reproduce:
- place any item in mixing basin (Gradient or no), water optional
- try to remove

Both Ian and I were able to reproduce this issue.

**Comment by LordMonoxide** [comment]
Were you shift-right-clicking with both hands empty?

**Comment by LordMonoxide** [comment]
This was a conflict with the CarryOn mod.  It overrides shift-right-click behaviour.  Gradient machines should be blacklisted in the CarryOn config.
