### ISSUE TITLE
Make forge hammers look less like battle axes

### ISSUE THREAD

**Issue by LordMonoxide** [LordMonoxide/gradient#89]

**Comment by Nexses** [comment]
![forge hammer 4](https://user-images.githubusercontent.com/7481118/29759470-746b7544-8b92-11e7-91e5-34e4d961eafa.png)

Spent 5 min trying paint again. Any sugestions to improve it?

**Comment by CaitlinTheAwesome** [comment]
well it doesn't look like a battle axe, so that's an improvement lol
